### PR TITLE
Feature/write collection

### PR DESCRIPTION
**Pull request by zacdezgeo**
Adds a collection object to the static STAC files generated.

### CODE REVIEW

**Comment by zacdezgeo** [comment]
@vincentsarago ; I'm getting an invalidated geometry when running `stac-check` on any activity file. Not sure, what exactly is causing the issue. I seem to conform to the [spec definition](https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md) even if using the `Linestring` type. Here's an example activity STAC item: https://gist.github.com/zacharyDez/3a36996f246529ec99c67e25e0028aa6

**Comment by vincentsarago** [comment]
using pystac for your item gives me an error about missing Datetime
```
item = pystac.Item.from_dict(a)
---------------------------------------------------------------------------
STACError                                 Traceback (most recent call last)
<ipython-input-3-12ae5258676d> in <cell line: 1>()
----> 1 item = pystac.Item.from_dict(a)

~/Dev/venv/py39/lib/python3.9/site-packages/pystac/item.py in from_dict(cls, d, href, root, migrate, preserve_dict)
    517         }
    518 
--> 519         item = cls(
    520             **{k: d.get(k) for k in pass_through_fields},  # type: ignore
    521             datetime=datetime,

~/Dev/venv/py39/lib/python3.9/site-packages/pystac/item.py in __init__(self, id, geometry, bbox, datetime, properties, start_datetime, end_datetime, stac_extensions, href, collection, extra_fields, assets)
    144         if datetime is None:
    145             if "start_datetime" not in properties or "end_datetime" not in properties:
--> 146                 raise STACError(
    147                     "Invalid Item: If datetime is None, "
    148                     "a start_datetime and end_datetime "

STACError: Invalid Item: If datetime is None, a start_datetime and end_datetime must be supplied.
```

**Comment by vincentsarago** [comment]
Note: to export the STAC Items to a pgstac database we might want to export the STAC Items and collection to a NewLine delimited JSON files instead of a static catalog

**Comment by zacdezgeo** [comment]
@vincentsarago any recommendations on how we should export the STAC items and a collection to a newline delimited JSON? Should we create it during the execution of `main.py` or provide some other way to post-process it?

Trying with: `find strava -type f -name "*.json" ! -name "collection.json" -print0 | xargs -0 -I {} jq -c . {} > strava/merged_stac_items.json`, but it's not fast.

**Comment by vincentsarago** [comment]
I think we could use pystac for this like in https://github.com/vincentsarago/MAXAR_opendata_to_pgstac/blob/main/generate.py

Sadly I don't think it will be fast, because pystac will also crawl all the directories 😓

**Pull request closed without merging**
